import { ScriptConfig } from '../types';
import { SupplierMapping, MASTER_SUPPLIER_MAPPINGS } from '../data/supplierMappings';

export function generatePythonScript(config: ScriptConfig, customMappings?: SupplierMapping[]): string {
  return generateSimpleBatchPythonScript(config);
}

export function generateSimpleBatchPythonScript(config: ScriptConfig): string {
  const isServiceAccount = config.authType === 'service_account';
  const batchSize = config.batchSize || 50;

  const authImports = isServiceAccount
    ? `from google.oauth2 import service_account`
    : `from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow`;

  const authFunction = isServiceAccount
    ? `def get_drive_service(credentials_file="service_account.json"):
    """Authenticate using Google Cloud Service Account credentials."""
    if not os.path.exists(credentials_file):
        raise FileNotFoundError(f"Service account file '{credentials_file}' not found.")
    creds = service_account.Credentials.from_service_account_file(
        credentials_file, scopes=SCOPES
    )
    return build("drive", "v3", credentials=creds)`
    : `def get_drive_service(credentials_file="credentials.json", token_file="token.json"):
    """Authenticate using OAuth 2.0 (browser pop-up)."""
    creds = None
    if os.path.exists(token_file):
        try:
            creds = Credentials.from_authorized_user_file(token_file, SCOPES)
        except Exception as e:
            logger.warning(f"Token could not be loaded: {e}. Re-authenticating...")

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            logger.info("Refreshing expired access token...")
            creds.refresh(Request())
        else:
            if not os.path.exists(credentials_file):
                raise FileNotFoundError(f"Credentials file '{credentials_file}' not found.")
            logger.info("Opening browser for Google Drive authorization...")
            flow = InstalledAppFlow.from_client_secrets_file(credentials_file, SCOPES)
            creds = flow.run_local_server(port=0)
            
        with open(token_file, "w") as token:
            token.write(creds.to_json())
            logger.info(f"Saved token to {token_file}")

    return build("drive", "v3", credentials=creds)`;

  const sharedDrivesParams = config.includeSharedDrives
    ? `supportsAllDrives=True,
            includeItemsFromAllDrives=True,`
    : ``;

  return `#!/usr/bin/env python3
"""
SIMPLE Google Drive Invoice Batch Downloader
=============================================
Features:
1. Search Google Drive for PDFs matching "invoice" keyword
2. Download matched files AS-IS (no renaming, no 3-line PDF nonsense)
3. Package into ZIPs: 50 files per batch (flat structure, no folders inside)
4. Clean, minimal code - no suppliers, no shortcuts, no overcomplications

Generated by GDrive Invoice Downloader Studio
"""

import io
import os
import re
import sys
import time
import random
import zipfile
import logging
from datetime import datetime
import pandas as pd
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseDownload
${authImports}

# ==============================================================================
# CONFIGURATION
# ==============================================================================
SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]

# Search keyword for invoices
SEARCH_KEYWORD = "invoice"

# Number of files per ZIP archive
BATCH_SIZE = ${batchSize}

# Output directories
OUTPUT_DIR = "./downloaded_invoices"
ZIPS_DIR = os.path.join(OUTPUT_DIR, "zip_batches")
TEMP_DOWNLOAD_DIR = os.path.join(OUTPUT_DIR, "temp_downloads")

# Rate limiting
RATE_LIMIT_DELAY = ${config.rateLimitDelaySec.toFixed(2)}
ENABLE_JITTER = ${config.enableJitter ? 'True' : 'False'}

# Logging setup
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("InvoiceDownloader")


# ==============================================================================
# AUTHENTICATION
# ==============================================================================
${authFunction}


# ==============================================================================
# GOOGLE DRIVE SEARCH
# ==============================================================================
def search_invoices(service, search_term="invoice"):
    """
    Simple Google Drive search for PDFs matching search_term.
    Returns list of file objects.
    """
    logger.info(f"Searching Google Drive for PDFs containing '{search_term}'...")
    
    query = f"name contains '{search_term}' and mimeType = 'application/pdf' and trashed = false"
    files = []
    page_token = None

    while True:
        try:
            res = service.files().list(
                q=query,
                spaces="drive",
                fields="nextPageToken, files(id, name, size, modifiedTime)",
                pageSize=100,
                pageToken=page_token,
                ${sharedDrivesParams}
            ).execute()

            batch_files = res.get("files", [])
            files.extend(batch_files)
            logger.info(f"  Found {len(batch_files)} files in this batch. Total so far: {len(files)}")

            page_token = res.get("nextPageToken")
            if not page_token:
                break
        except HttpError as error:
            logger.error(f"Google Drive API error: {error}")
            break

    logger.info(f"Total PDFs found: {len(files)}")
    return files


# ==============================================================================
# DOWNLOAD & BATCH ZIP CREATION
# ==============================================================================
def download_file(service, file_id, destination_path, filename):
    """Downloads single file with chunked stream & exponential backoff."""
    max_retries = 5
    request = service.files().get_media(fileId=file_id)

    for attempt in range(1, max_retries + 1):
        try:
            with open(destination_path, "wb") as fh:
                downloader = MediaIoBaseDownload(fh, request, chunksize=5 * 1024 * 1024)
                done = False
                while not done:
                    _, done = downloader.next_chunk()
            return True
        except HttpError as err:
            if err.resp.status in [429, 500, 502, 503, 504]:
                wait_time = 2 ** attempt
                logger.warning(f"Rate limited on {filename}. Waiting {wait_time}s (retry {attempt}/{max_retries})...")
                time.sleep(wait_time)
            else:
                logger.error(f"HTTP Error {err.resp.status} on {filename}: {err}")
                return False
        except Exception as e:
            logger.error(f"Download failed for {filename}: {e}")
            return False
    return False


def process_batches_and_zip(service, files):
    """
    Downloads files and packages them into ZIP files in batches of 50.
    NO folder organization - flat ZIP structure.
    """
    os.makedirs(TEMP_DOWNLOAD_DIR, exist_ok=True)
    os.makedirs(ZIPS_DIR, exist_ok=True)

    total_files = len(files)
    num_batches = (total_files + BATCH_SIZE - 1) // BATCH_SIZE
    logger.info(f"Splitting {total_files} files into {num_batches} ZIP batch(es) of {BATCH_SIZE} files each.")

    created_zips = []

    for batch_num in range(1, num_batches + 1):
        start_idx = (batch_num - 1) * BATCH_SIZE
        end_idx = min(start_idx + BATCH_SIZE, total_files)
        batch_slice = files[start_idx:end_idx]

        zip_filename = f"invoices_batch_{batch_num:02d}_{start_idx + 1}_to_{end_idx}.zip"
        zip_path = os.path.join(ZIPS_DIR, zip_filename)

        print("-" * 70)
        logger.info(f"Processing Batch {batch_num}/{num_batches}: Files {start_idx + 1} to {end_idx}")
        logger.info(f"Target Archive: {zip_filename}")

        batch_temp_files = []

        # Download batch items
        for i, file_item in enumerate(batch_slice, 1):
            file_id = file_item["id"]
            filename = file_item["name"]
            
            file_dest = os.path.join(TEMP_DOWNLOAD_DIR, filename)

            logger.info(f"[{i}/{len(batch_slice)}] Downloading: {filename}")
            
            if not os.path.exists(file_dest):
                # Rate Limiter
                if RATE_LIMIT_DELAY > 0:
                    delay = RATE_LIMIT_DELAY
                    if ENABLE_JITTER:
                        delay += random.uniform(-0.15 * RATE_LIMIT_DELAY, 0.15 * RATE_LIMIT_DELAY)
                    delay = max(0.05, delay)
                    time.sleep(delay)

                success = download_file(service, file_id, file_dest, filename)
                if not success:
                    logger.error(f"Failed to download {filename}, skipping from archive.")
                    continue
            
            batch_temp_files.append(file_dest)

        # Compress into ZIP with FLAT structure (no folders inside)
        logger.info(f"Packing {len(batch_temp_files)} files into {zip_filename}...")
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for file_path in batch_temp_files:
                # Add file to ZIP at root level (no subdirectories)
                zipf.write(file_path, arcname=os.path.basename(file_path))

        zip_size_mb = os.path.getsize(zip_path) / (1024 * 1024)
        logger.info(f"[SUCCESS] Created ZIP: {zip_path} ({zip_size_mb:.2f} MB)")
        created_zips.append((zip_filename, zip_size_mb, len(batch_temp_files)))

        # Clean up temp files for this batch
        for file_path in batch_temp_files:
            try:
                if os.path.exists(file_path):
                    os.remove(file_path)
            except Exception:
                pass

    return created_zips


# ==============================================================================
# MAIN ENTRY POINT
# ==============================================================================
def main():
    print("=" * 70)
    print("  SIMPLE GOOGLE DRIVE INVOICE BATCH DOWNLOADER")
    print("  (Flat ZIP structure, 50 files per batch)")
    print("=" * 70)

    try:
        service = get_drive_service()
    except Exception as e:
        logger.error(f"Authentication failed: {e}")
        sys.exit(1)

    # Search for invoices
    files = search_invoices(service, SEARCH_KEYWORD)

    if not files:
        logger.warning("No PDF files found matching search term.")
        return

    # Process files into 50-per-batch ZIPs
    created_zips = process_batches_and_zip(service, files)

    print("=" * 70)
    print("ALL BATCHES COMPLETE!")
    print(f"Total PDFs Found:         {len(files)}")
    print(f"Total ZIP Archives:       {len(created_zips)}")
    print("-" * 70)
    print("Created ZIP Archives (50 files per batch, flat structure):")
    for name, size_mb, count in created_zips:
        print(f"  * {name} ({count} files, {size_mb:.2f} MB)")
    print(f"ZIPs Location:            {os.path.abspath(ZIPS_DIR)}")
    print("=" * 70)


if __name__ == "__main__":
    main()
`;
}

export function generateRequirementsTxt(authType: string): string {
  return `pandas>=2.0.0
openpyxl>=3.1.0
google-api-python-client>=2.115.0
google-auth-httplib2>=0.2.0
google-auth-oauthlib>=1.2.0
`;
}

export function generateReadmeMd(config: ScriptConfig): string {
  return `# Simple Google Drive Invoice Batch Downloader

**CLEAN & SIMPLE:**
- Searches Google Drive for PDFs containing "invoice" keyword
- Downloads files AS-IS (no renaming, no 3-line PDF nonsense)
- Batches into ZIPs: 50 files per batch
- Flat ZIP structure (no folder organization inside)

## 🚀 Quick Setup

\`\`\`bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Place credentials.json in this directory

# 3. Run the script
python3 batch_download_invoices_zip.py
\`\`\`

## 📦 What the script creates
- \`./downloaded_invoices/zip_batches/invoices_batch_01_1_to_50.zip\`
- \`./downloaded_invoices/zip_batches/invoices_batch_02_51_to_100.zip\`
- etc.

Each ZIP contains exactly 50 PDF files at the root level (no nested folders).
`;
}

// Keep legacy function for backwards compatibility
export function generateBatchSheetPythonScript(config: ScriptConfig, customMappings?: SupplierMapping[]): string {
  return generateSimpleBatchPythonScript(config);
}
